from typing import Dict, List, Set
from parsers.dependency_graph import DependencyGraph
import re

class ImpactAnalyzer:
    def __init__(self, dependency_graph: Dict):
        self.graph = DependencyGraph(dependency_graph, dependency_graph)  # Simplified
    
    def analyze_pr_impact(self, changed_files: List[Dict]) -> Dict:
        """Analyze impact of PR changes"""
        impact_report = {
            "changed_files": [],
            "affected_backend": [],
            "affected_frontend": [],
            "affected_tests": [],
            "risk_level": "LOW"
        }
        
        all_affected = set()
        
        for file_info in changed_files:
            filename = file_info["filename"]
            
            # Find nodes in this file
            changed_nodes = self._find_nodes_in_file(filename)
            
            for node_id in changed_nodes:
                # Get all affected nodes (BFS traversal)
                affected = self.graph.get_affected_nodes(node_id)
                all_affected.update(affected)
                
                impact_report["changed_files"].append({
                    "file": filename,
                    "node": node_id
                })
        
        # Categorize affected nodes
        for node_id in all_affected:
            node_info = self.graph.get_node_info(node_id)
            if not node_info:
                continue
            
            if node_info.get("repo") == "backend":
                if node_info.get("type") == "test":
                    impact_report["affected_tests"].append(node_info)
                else:
                    impact_report["affected_backend"].append(node_info)
            
            elif node_info.get("repo") == "frontend":
                if "spec.ts" in node_info.get("file", ""):
                    impact_report["affected_tests"].append(node_info)
                else:
                    impact_report["affected_frontend"].append(node_info)
        
        # Calculate risk level
        impact_report["risk_level"] = self._calculate_risk(impact_report)
        
        return impact_report
    
    def _find_nodes_in_file(self, filename: str) -> List[str]:
        """Find all nodes defined in a file"""
        nodes = []
        for node in self.graph.graph["nodes"]:
            if filename in node.get("file", ""):
                nodes.append(node["id"])
        return nodes
    
    def _calculate_risk(self, impact: Dict) -> str:
        """Calculate risk level based on impact scope"""
        total_affected = (
            len(impact["affected_backend"]) + 
            len(impact["affected_frontend"]) +
            len(impact["affected_tests"])
        )
        
        if total_affected == 0:
            return "LOW"
        elif total_affected < 5:
            return "MEDIUM"
        elif total_affected < 10:
            return "HIGH"
        else:
            return "CRITICAL"
    
    def generate_comment(self, impact: Dict) -> str:
        """Generate markdown comment for PR"""
        comment = "## 🎯 Impact Analysis\n\n"
        
        # Summary
        comment += f"**Risk Level:** `{impact['risk_level']}`\n\n"
        comment += f"**Total Affected:** {len(impact['affected_backend']) + len(impact['affected_frontend'])} files\n\n"
        
        # Changed files
        comment += "### 📝 Changes Detected\n"
        for change in impact["changed_files"]:
            comment += f"- `{change['file']}` → `{change['node']}`\n"
        comment += "\n"
        
        # Backend impact
        if impact["affected_backend"]:
            comment += "### 🔄 Backend Impact\n"
            for node in impact["affected_backend"][:5]:  # Show max 5
                comment += f"- `{node['id']}` ({node['file']})\n"
            if len(impact["affected_backend"]) > 5:
                comment += f"- ... and {len(impact['affected_backend']) - 5} more\n"
            comment += "\n"
        
        # Frontend impact
        if impact["affected_frontend"]:
            comment += "### 🌐 Frontend Impact\n"
            for node in impact["affected_frontend"][:5]:
                comment += f"- `{node['id']}` ({node['file']})\n"
            if len(impact["affected_frontend"]) > 5:
                comment += f"- ... and {len(impact['affected_frontend']) - 5} more\n"
            comment += "\n"
        
        # Tests
        if impact["affected_tests"]:
            comment += "### ⚠️ Tests to Update\n"
            for node in impact["affected_tests"][:5]:
                comment += f"- `{node['id']}` ({node['file']})\n"
            if len(impact["affected_tests"]) > 5:
                comment += f"- ... and {len(impact['affected_tests']) - 5} more\n"
            comment += "\n"

        comment += "\n---\n*Generated by Impact Analyzer*"

        return comment
